### ISSUE TITLE
CPU 100% load

### ISSUE THREAD

**Issue by herculeshssj** [jenkinsci/telegram-notifications-plugin#11]
Hi,

I recently discovered that the plugin consumes 100% of the CPU. By disabling the plugin, the CPU consumption normalizes.

In the link https://wiki.jenkins.io/display/JENKINS/Telegram+Notification+Plugin I saw that another user had the same problem.

I'm using Jenkins v2.89.4.

**Comment by AndreyShamis** [comment]
Same. 1 of 8 CPUs always 100% when plagin enabled
