### ISSUE TITLE
Add "Token Macro Plugin" support

### ISSUE THREAD

**Issue by mstrdev** [jenkinsci/telegram-notifications-plugin#13]
I want to publish my git changes ${GITCHANGELOG} to telegram from Git Changelog Plugin.
But this plugin does not consume a tokens

**Comment by alekseiko** [comment]
Hi, could you please give us more details, what kind of tokens do you need?

**Comment by mstrdev** [comment]
I mean data from this plugin https://wiki.jenkins.io/display/JENKINS/Git+Changelog+Plugin. I want to print information from git commit to telegram channel (token $GITCHANGELOG)

**Comment by nikitabelonogov** [comment]
The point of an issue is to add compatibility with [Token Macro Plugin](https://wiki.jenkins.io/display/JENKINS/Token+Macro+Plugin) as I understand.
