### ISSUE TITLE
How to install latest version from git ?

### ISSUE THREAD

**Issue by mausspb** [jenkinsci/telegram-notifications-plugin#31]
Hi.
How i can compile hpi file for install latest version from git ?

**P.S.**: I want to use tg noti with pipeline

**Comment by nikitabelonogov** [comment]
Hi 

To build a plugin, run `mvn install`. This will create the file _./target/telegram-notifications.hpi_ that you can deploy to Jenkins.

**Comment by mausspb** [comment]
Thsk you so much !)

**Comment by mausspb** [comment]
In java-11-openjdk-amd64 version i am  get error java-11-openjdk-amd64 `Unable to find javadoc command`, because this file not exist.  I not a specialist with java ...
May be you will writed instruction for compile ?
And it would be great if you will add runner or other CI for **autogenerate** artefacts - **hpi** file ......

**Comment by wlad031** [comment]
My suggestion is to not use java versions younger than 8 :) There are a lot of problems to compile old code base for them
