### ISSUE TITLE
Refactor for compatibility with Pipeline jobs

### ISSUE THREAD

**Issue by Nosk14** [jenkinsci/telegram-notifications-plugin#9]
It would be nice if this plugin can be used in Pipeline jobs too.
There is more info here: https://jenkins.io/blog/2016/05/25/update-plugin-for-pipeline/

**Comment by ZhdanovR** [comment]
+1

**Comment by danielemontesi** [comment]
+1

**Comment by gleam-ru** [comment]
+1

**Comment by dot1q** [comment]
+1

**Comment by o1egl** [comment]
+1

**Comment by b0dh1** [comment]
+1

**Comment by mgomersbach** [comment]
+1
...and [somebody did it](https://github.com/Azzill/telegram-notifications-plugin/commit/927fcfa169619e63b73df7e3a8757ae06866212b)
